### ISSUE TITLE
msgctxt not managed?

### ISSUE THREAD

**Issue by leolivier** [a3510377/vscode-gettext#1]
I have in a .po file 2 translations like this:
#: members/models.py:34
msgctxt "CSV Field"
msgid "family"
msgstr "famille"

#: members/models.py:55
msgctxt "not CSV Field"
msgid "family"
msgstr "famille"

vscode-gettext does think that there is an "Duplicate message definition" error but as I have 2 different contexts, there is no duplicate.
![image](https://github.com/a3510377/vscode-gettext/assets/4014752/1a30578a-54c0-4ad7-9106-89ac2f0eb17c)

**Comment by qmkcat** [comment]
![image](https://github.com/a3510377/vscode-gettext/assets/70706886/41e8c1f4-5d0b-4be5-b98f-8166e49c1eb2)

Sorry I just saw it now
It has been fixed and is ready for release, but we have to wait for certification.

**Comment by qmkcat** [comment]
![image](https://github.com/a3510377/vscode-gettext/assets/70706886/d1625099-6d3d-4fa0-b2b3-d0c1bdbe2470)
Okay, the verify is over~~

**Comment by leolivier** [comment]
just reinstalled and test, it works, thank you!
